### ISSUE TITLE
Invalid hook call error in Chat.js file while using useParams hook. 

### ISSUE THREAD

**Issue by developinghands** [developinghands/Whatsapp-Clone#4]
# Version
<img src="https://img.shields.io/badge/react-16.14.0-brightgreen">
<img src="https://img.shields.io/badge/react--router--dom-5.2.0-brightgreen">

# Error
While doing below
```javascript
const { roomId } = useParams();
```
```
Error in /turbo_modules/react@17.0.1/cjs/react.development.js (1476:13)
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```
## File
[Chat.js](http://github.com/developinghands/Whatsapp-Clone/blob/master/src/Chat.js)

**Comment by developinghands** [comment]
# Dependency Missing
<img src="https://img.shields.io/badge/react--router-5.2.0-blue"/>
Issue fixed after adding `react-router` in dependency #

**Comment by hichamob** [comment]
@developinghands can you help me i have the same probleme and i don't know what can i do ?

**Comment by developinghands** [comment]
> @developinghands can you help me i have the same probleme and i don't know what can i do ?

Have you added **react-router:"^5.2.0"** dependency in package.json file in your project?
![image](https://user-images.githubusercontent.com/56860462/108605346-959b1c00-73d9-11eb-9c5a-de4e0f2b1c61.png)

**Comment by hichamob** [comment]
@developinghands  non i did have it but now i add it and also the same probleme  i don't konw what can i do

**Comment by Jonnevie** [comment]
Once you add the dependency in package.json, you would need to do a 'npm i' to see the impact.
